REPLACE INTO `role` (ROLE_ID, ROLE) VALUES (1,'USER');
REPLACE INTO `role` (ROLE_ID, ROLE) VALUES (2,'ADMIN');
#REPLACE INTO `configuration` (CONFIGURATION_ID, CONFIGNAME, CONFIGVALUE) VALUES (1,'minimumloginscore', 60);
#REPLACE INTO `configuration` (CONFIGURATION_ID, CONFIGNAME, CONFIGVALUE) VALUES (2,'maximumloginrisk', 50);
#REPLACE INTO `configuration` (CONFIGURATION_ID, CONFIGNAME, CONFIGVALUE) VALUES (3,'minimumstepupscore', 60);
#REPLACE INTO `configuration` (CONFIGURATION_ID, CONFIGNAME, CONFIGVALUE) VALUES (4,'maximumstepuprisk', 50);
#REPLACE INTO `configuration` (CONFIGURATION_ID, CONFIGNAME, CONFIGVALUE) VALUES (5,'minimumformscore', 60);
#REPLACE INTO `configuration` (CONFIGURATION_ID, CONFIGNAME, CONFIGVALUE) VALUES (6,'maximumformrisk', 50);
